### ISSUE TITLE
Blank Configurations page

### ISSUE THREAD

**Issue by elazar** [sasanrose/phpredmin#57]
When I click Configurations in the navigation bar, I get this:

![screen shot 2014-06-30 at 2 08 12 pm](https://cloud.githubusercontent.com/assets/15487/3434421/fb8e3d82-0089-11e4-9959-593e1f075af7.png)

Looking in `logs/fpm-fcgi/2014-06-30.log` turned up this:

```
[2014-06-30 14:06:40] [184.186.16.104]  [warning]: Invalid argument supplied for foreach() on /srv/www/phpredmin/views/welcome/config.php:4
```

**Comment by sasanrose** [comment]
What is you Redis version?

**Comment by elazar** [comment]
Not sure offhand what version was running on the date of this issue, but I'm currently running 2.8.6. If you can't replicate it under that version, I'd say go ahead and close this issue.

**Comment by Ritbit** [comment]
I'm haveing a blank configuration page as well, I'm using the latest phpredmin with Redis 2.8.24 (Via Amazon ElastiCache) on php 5.5.31 with nginx/php-fpm. Unfortunately no error show up in logfiles.

Any hints?
