### ISSUE TITLE
Make it available through composer

### ISSUE THREAD

**Issue by drAlberT** [sasanrose/phpredmin#72]
It would be nice to be able to install phpredmin via **[composer](https://getcomposer.org/)** ..

I'm using this project in [faktiva/php-admin-tk](https://github.com/faktiva/php-admin-tk) and will be nice to require this prj in composer .. nowadays I have required it manually .. see my composer.json for reference

**Comment by drAlberT** [comment]
@sasanrose what do you think?  I could implement it if you agree ..

**Comment by sasanrose** [comment]
@drAlberT can you please explain more about the requirements and your solution?

**Comment by drAlberT** [comment]
I'm simply asking to add a `composer.json` file in the root of the project in order to be able to submit it to packagist.org .. this way users could use this project with composer too, simply invoking `composer require sasanrose/phpredmin` 

As the cost of this enhancement is very cheap I think it could be done .. I can do it for you if you want

**Comment by sasanrose** [comment]
@drAlberT Yeah I know about composer. But my point is that is not how you should use composer. That is not what composer is for. PHPRedmin is not really a requirement for any project. And current version of PHPRedmin does not have any specific dependencies itself that need composer.

**Comment by joturako** [comment]
My thought: think Laravel & your website that used Laravel. While Laravel is available through composer, your website should not. This project is not a framework nor an package that offers functions to another package, it's the final product ready to be consumed.

If you wanted to include this inside your package of utilities, you may need to maintain a modified version yourself.

**Comment by drAlberT** [comment]
@sasanrose my project has .. :(  So I have to maintain a fork just to have the project "cleaned" from composer.json file? ... ;(((

**Comment by drAlberT** [comment]
OK, never mind .. I'll maintain a fork :)

Thanks anyway guys
