### ISSUE TITLE
Latest build does not work in PHP7

### ISSUE THREAD

**Issue by AniaSoft** [sasanrose/phpredmin#75]
Hi, Please make it work with PHP7. Thank you!

**Comment by devdesco-ceo** [comment]
Mine works just fine with latest PHP7

**Comment by drAlberT** [comment]
mine too

**Comment by sasanrose** [comment]
@AniaSoft Can you provide more information? Error messages or steps to reproduce this

**Comment by sasanrose** [comment]
I'll close the issue since there were no more information provided
