### ISSUE TITLE
500 internal error server php_value short_open_tag 1

### ISSUE THREAD

**Issue by bonsdawende** [sasanrose/phpredmin#77]
Hi,

I got the message error 500 when I tried phpredmin with Apache : http:X.X.X.X/phpredmin

I installed Apache/2.4.23 and PHP 7. 

The message error is : 
/var/www/html/phpredmin/public/.htaccess: Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration

Here is the content of my .htaccess: 
php_value short_open_tag 1

My phpredmin.conf file is : 
Alias /phpredmin /var/www/html/phpredmin/public
<Directory /var/www/html/phpredmin/>
   AllowOverride All
   <IfModule mod_authz_core.c>
     # Apache 2.4
     <RequireAny>
       Require ip 127.0.0.1
       Require local
     </RequireAny>
   </IfModule>

   <IfModule !mod_authz_core.c>
     # Apache 2.2
     Order Deny,Allow
     Deny from All
     Allow from 127.0.0.1
     Allow from ::1
   </IfModule>
</Directory>

Anyone have idea about this problem ? Thanks

**Comment by bronco0** [comment]
Hi,

This file can be deleted.

But the php module is activated ?

Thanks

**Comment by sasanrose** [comment]
I blieve you can delete this file, but as far as I know, the last time I tested PHPRedmin with a PHP7 machine there were lots of errors. And to be honest I do not have any plans anytime soon to port this to PHP7. If you can make it compatible with PHP7 I'll be more than happy.

**Comment by bronco0** [comment]
Hi,

I have installed PHPRedmin with PHP 7.1 without problem.
I just deleted this file.

Thanks
