### ISSUE TITLE
Redis admin not working

### ISSUE THREAD

**Issue by Nirjonadda** [sasanrose/phpredmin#81]
Hello,

I have uploading all files to my webserver but Its not working , Just showing Index of /redis : https://s17.postimg.org/kdqrns25b/Screen_Shot00215.png

Thanks

**Comment by joturako** [comment]
Hi, it seems you have to go to the public folder as seen in that picture. The index.php file is in that folder.

**Comment by Nirjonadda** [comment]
The index.php file are not in this folder.

**Comment by joturako** [comment]
Can you find the index.php file at  /redis/public/index.php ? It should be there.

**Comment by Nirjonadda** [comment]
Oh, then we need open /redis/public/index.php on my web browser and its work. Redis Stats are not work: https://s18.postimg.org/7gkawba2f/Screen_Shot00217.png

**Comment by joturako** [comment]
@Nirjonadda you can follow the instruction in the **Statistics** section of the [README.md](https://github.com/sasanrose/phpredmin#statistics) file

**Comment by sasanrose** [comment]
I think the instructions are clear. Will close this issue
