### ISSUE TITLE
Cannot change default password

### ISSUE THREAD

**Issue by aconital** [sasanrose/phpredmin#88]
I installed phpredmin by adding your instruction to my docker-compose.yml file.  However -PHPREDMIN_AUTH_PASSWORD = mypassword does not set the password. Is there something I can do about this?

**Comment by joturako** [comment]
@aconital please beware that you will need to set `PHPREDMIN_AUTH_PASSWORD = password_hash('mypassword')` with `password_hash` is the php function. So it's going to be like `PHPREDMIN_AUTH_PASSWORD = ACXOWMEO@`

**Comment by aconital** [comment]
thank you!
