### ISSUE TITLE
Hi,Thanks for your job!! I have a bug to report...

### ISSUE THREAD

**Issue by lihongming** [sasanrose/phpredmin#9]
index 1e85d4a..5f99b70 100644
--- a/views/welcome/info.php
+++ b/views/welcome/info.php
@@ -66,7 +66,7 @@
                     <?=$this->info['connected_slaves']?>
                 </td>
             </tr>
-        <? } ?>
+        <?php } ?>
         <tr>
             <td>
                 Used Memory:

it show a 500 error....

so I change   <? } ?> to   <?php } ?> ,

**Comment by sasanrose** [comment]
Sorry for delay

There is no short open tag except <?= in codes now. So there should be any problem, because it's available since php 5.4.0
